apiVersion: enterprises.upmc.com/v1
kind: ElasticsearchCluster
metadata:
  name: es-cluster
  namespace: efk
spec:
  kibana:
    image: docker.elastic.co/kibana/kibana-oss:6.1.3
  cerebro:
    image: upmcenterprises/cerebro:0.6.8
  elastic-search-image: upmcenterprises/docker-elasticsearch-kubernetes:6.1.3_0
  # client-node-replicas: 3
  # master-node-replicas: 2
  # data-node-replicas: 3
  use-ssl: false
  client-node-replicas: 1
  master-node-replicas: 1
  data-node-replicas: 1
  network-host: 0.0.0.0
  zones: []
  data-volume-size: 10Gi
  java-options: "-Xms256m -Xmx256m"
  snapshot:
    scheduler-enabled: false
    # bucket-name: elasticsnapshots99
    # cron-schedule: "@every 2m"
    # image: upmcenterprises/elasticsearch-cron:0.0.4
  storage:
    storage-class: default
    volume-reclaim-policy: Delete
  resources:
    requests:
      memory: 512Mi
      cpu: 500m
    limits:
      memory: 6144Mi
      cpu: '3'