apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
clusterName: devk8s
kubernetesVersion: v1.13.1
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  certSANs:
  - "devk8s"
  - "10.6.201.174"
  - "192.168.137.102"
controlPlaneEndpoint: "devk8s:6443"
---
apiVersion: kubeproxy.config.k8s.io/v1alpha1
kind: KubeProxyConfiguration
mode: "ipvs"
