apiVersion: kubeadm.k8s.io/v1beta1
kind: ClusterConfiguration
kubernetesVersion: v1.13.0
networking:
  podSubnet: 10.244.0.0/16
apiServer:
  certSANs:
  - "internalk8s.10010sh.cn"
  - "10.6.201.175"
  - "10.6.201.176"
  - "10.6.201.177"
controlPlaneEndpoint: "internalk8s.10010sh.cn:6443"
kubeProxy:
  config:
    featureGates:
      SupportIPVSProxyMode: true
    mode: ipvs